name: kylin-video
version: "1.1.6.2"
summary: Kylin Video
description: |
  Qt5 Mplayer and MPV front-end, with basic features like playing
  videos and audios to more advanced features. It supports both x86
  and ARM platform, and supports most of the audio and video formats.

  Features currently included:
   * Display the application icon
   * Add network-bind plug to solve this error: QtSingleCoreApplication listen on local socket failed
   * Support debian and snap

grade: stable #devel
confinement: strict #devmode

apps:
  kylin-video:
    command: desktop-launch $SNAP/usr/bin/kylin-video
    plugs: [home, unity7, network, network-bind, desktop, pulseaudio, x11]

parts:
  kylin-video:
    plugin: qmake
    source: .
    qt-version: qt5
    build-packages:
      - build-essential
      - g++
      - qtbase5-dev
      - qt5-qmake
      - qtscript5-dev
      - qttools5-dev-tools
      - zlib1g-dev
    stage-packages:
      - libc6
      - libgcc1
      - libqt5core5a
      - libqt5gui5
      - libqt5network5
      - libqt5widgets5
      - libstdc++6
      - zlib1g
      - mplayer
      - mpv
      - mesa-vdpau-drivers
      - libxcb1
      - libglu1-mesa
      - freeglut3
      - libgpm2
      - qttranslations5-l10n
    after: [desktop-qt5]
